apiVersion: skaffold/v2beta16
kind: Config
profiles:
- name: prod
  deploy:
    statusCheckDeadlineSeconds: 90
    helm:
      releases:
      - name: prod
        chartPath: ./osdfir-infrastructure/charts/osdfir-infrastructure
        skipBuildDependencies: true
        recreatePods: false
        setValues:
          global.grr.enabled: false
          global.yeti.enabled: false
          global.openrelik.enabled: false
        setValueTemplates:
          timesketch.image.repository: "{{.IMAGE_FULLY_QUALIFIED_us_central1_docker_pkg_dev_osdfir_registry_timesketch_v2_timesketch}}"
          timesketch.image.tag: "{{.IMAGE_TAG_us_central1_docker_pkg_dev_osdfir_registry_timesketch_v2_timesketch}}"
          timesketch.opensearch.image.repository: "{{.IMAGE_FULLY_QUALIFIED_us_central1_docker_pkg_dev_osdfir_registry_timesketch_v2_dev}}"
          timesketch.opensearch.image.tag: "{{.IMAGE_TAG_us_central1_docker_pkg_dev_osdfir_registry_timesketch_v2_dev}}"
