{{- $cert := genSelfSignedCert "executable-signing" nil (list "executable-siging")  3650 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grr-executable-signing-keys
  {{- if .Values.grr.namespace }}
  namespace: {{ .Values.grr.namespace }}
  {{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
    {{- if .Values.global.generateExeSignCert }}
    exe-sign-private-key.pem: {{ $cert.Key| b64enc }}
    exe-sign.crt: {{ $cert.Cert | b64enc }}
    {{- else }}
    exe-sign-private-key.pem: {{ .Files.Get "certs/exe-sign-private-key.pem" | b64enc }}
    exe-sign-public-key.pem: {{ .Files.Get "certs/exe-sign-public-key.pem" | b64enc }}
    {{- end }}
